import {
  Baby,
  BookOpen,
  Cake,
  Cog,
  IceCreamCone,
  PiggyBank,
  Send,
  Bike,
  Bus,
  Car,
  CalendarClock,
  Carrot,
  ChefHat,
  CircleEllipsis,
  CupSoda,
  Droplet,
  Dumbbell,
  Flame,
  Fuel,
  Gift,
  GraduationCap,
  HandHeart,
  HeartPulse,
  Home,
  Landmark,
  MonitorPlay,
  PartyPopper,
  PawPrint,
  Phone,
  Pill,
  Plane,
  Repeat,
  Scissors,
  Shield,
  Shirt,
  ShoppingCart,
  TrendingUp,
  Utensils,
  Wallet,
  Wifi,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

/** Catálogo de ícones disponíveis para categorias personalizadas. */
export const CATEGORY_ICONS: Record<string, LucideIcon> = {
  utensils: Utensils,
  carrot: Carrot,
  "shopping-cart": ShoppingCart,
  "chef-hat": ChefHat,
  bike: Bike,
  "cup-soda": CupSoda,
  fuel: Fuel,
  flame: Flame,
  home: Home,
  droplet: Droplet,
  zap: Zap,
  wifi: Wifi,
  phone: Phone,
  bus: Bus,
  "heart-pulse": HeartPulse,
  pill: Pill,
  dumbbell: Dumbbell,
  "monitor-play": MonitorPlay,
  shirt: Shirt,
  scissors: Scissors,
  "graduation-cap": GraduationCap,
  "party-popper": PartyPopper,
  repeat: Repeat,
  "calendar-clock": CalendarClock,
  wrench: Wrench,
  car: Car,
  landmark: Landmark,
  shield: Shield,
  baby: Baby,
  "book-open": BookOpen,
  cake: Cake,
  cog: Cog,
  "ice-cream-cone": IceCreamCone,
  "piggy-bank": PiggyBank,
  send: Send,
  gift: Gift,
  "hand-heart": HandHeart,
  "paw-print": PawPrint,
  plane: Plane,
  wallet: Wallet,
  "trending-up": TrendingUp,
  "circle-ellipsis": CircleEllipsis,
};

export const CATEGORY_ICON_KEYS = Object.keys(CATEGORY_ICONS);

export function categoryIcon(name?: string | null): LucideIcon {
  if (!name) return CircleEllipsis;
  return CATEGORY_ICONS[name] ?? CircleEllipsis;
}
